### ISSUE TITLE
Share example in PS rclone config

### ISSUE THREAD

**Issue by AndriySidliarskiy** [badouralix/rclone-lambda-sync#1]
Can you share exaple how you configure PS value for rclone config

**Comment by badouralix** [comment]
Usually I create the config locally first with <https://rclone.org/docs/#configure>

```bash
rclone config create "source" ...
rclone config create "destination" ...
```

This creates a local file that looks like this

```bash
$ cat ~/.config/rclone/rclone.conf
[source]
...

[destination]
...
```

This content is the actual value stored in SSM

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/19719047/144329662-cb0761db-ba3c-46db-8ef3-e8c5b6ec138f.png">

Either using the console or this one-liner

```bash
aws ssm put-parameter --region eu-west-3 --name rclone-config --type SecureString --value file://$HOME/.config/rclone/rclone.conf --description "Entire rclone.conf for rclone-lambda"
```

Let me know if this is enough information, I'll add these details in the README

**Comment by badouralix** [comment]
Closing this now, feel free to re-open if more information is needed
